#@host=http://backend-inscripcion.local/api
@host=https://backend-inscripciones.admision.uni.edu.pe/api

### GET request to example server
GET {{host}}/exam-simulations

### POST request to search for simulation applicants
POST {{host}}/simulation-applicants/search
Content-Type: application/json

{
  "dni": "43566014",
  "email": "caty_matias27@hotmail.com"
}

### POST request to register a new simulation applicant
POST {{host}}/simulation-applicants
Content-Type: application/json

{
  "dni": "15256639",
  "last_name_father": "Perez",
  "last_name_mother": "Garcia",
  "first_names": "Juan Carlos",
  "email": "lolo123@email.com",
  "phone_mobile": "987654321",
  "phone_other": "012345678"
}

### POST request to register a new simulation applicant
PUT {{host}}/simulation-applicants/7e7b4868-69e2-447d-93ca-d58714db189d
Content-Type: application/json

{
  "dni": "15256639",
  "last_name_father": "Perez",
  "last_name_mother": "Garcia",
  "first_names": "Alan",
  "email": "lolo123@email.com",
  "phone_mobile": "987654321",
  "phone_other": "012345678"
}

### Descripción: Sube la foto del carné.
### Requisitos: Imagen (jpg, png) max 2MB.
### Nota: En clientes REST como Postman/Insomnia se usa "Multipart Form". Aqui se simula la petición.
POST {{host}}/api/simulation-applicants/{{uuid}}/upload-photo
Content-Type: multipart/form-data; boundary=boundary
Accept: application/json

--boundary
Content-Disposition: form-data; name="photo"; filename="foto.jpg"
Content-Type: image/jpeg

< ./path/to/local/photo.jpg
--boundary--

### Descripción: Obtiene toda la información del postulante usando su UUID.
GET {{host}}/simulation-applicants/947b3a1b-d5c1-4b65-99bf-6099b9dbb355
Accept: application/json

### Descripción: Obtiene toda la información del postulante usando su UUID.
GET {{host}}/simulation-applicants/fd4f2608-4f96-4ab8-9c8b-5ba33e0e2293
Accept: application/json

### Status photo
GET {{host}}/simulation-applicants/20f53e0d-4c76-455e-a2c0-09814c261f0c/photo-status
Accept: application/json

### Confirmar datos
PUT {{host}}/simulation-applicants/confirm
Content-Type: application/json

{
  "uuid": "fd4f2608-4f96-4ab8-9c8b-5ba33e0e2293"
}

### Process
GET {{host}}/simulation-applicants/fd4f2608-4f96-4ab8-9c8b-5ba33e0e2293/status